version: '3'
services:
  migration:
    build:
      dockerfile: ./docker/migration/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
  backend:
    build:
      dockerfile: ./docker/app/Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    links:
      - database
  database:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
